services:
  todolist-app:
    container_name: todolist-app
    #build: .
    image: todolist-app:0.0.0
    ports: 
    - "3000:3000"
    env_file: .env
    networks:
      - network-postgres 

### declaration of external network
networks:
  network-postgres:
    name: network-postgres
      